spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  profiles:
    active: dev

#  mvc:
#    static-path-pattern: /static/**

# 修改配置文件 加上static-path-pattern: /static/**





