spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_blog_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#logging:
#  config: src/main/resources/logback-spring.xml
#  level:
#    root: info
#    com.learn.blog_demo: debug
#  file:
#    path: log/blog-dev.log


server:
  port: 8080



